### ISSUE TITLE
OpenShelter webservice map stops updating turbo subscription after some time

### ISSUE THREAD

**Issue by MisterChalmers** [chalmersproject/openshelter#3] opened 2023-08-15 03:31 UTC
Something is breaking turbo stream subscriptions; And I think it only happens when deployed to `fly.io`. After some minutes (an hour maybe?) the `Shelter Location Markers` on the map stop live-updating. 

On ShelterMeasurement commit, ActiveRecord is supposed to emit a event to the shelter-data turbo stream that has the `@shelter_measurment` data in it.

This functionality works as expected when running locally on my laptop. But when deployed to `fly.io` this functionality breaks after some time. The map no longer live updates it's markers. And in the rails logs I can't see the turbo-stream event trigger anymore.

**Comment by zach-c-d** [comment] 2023-08-23 00:20
If the problem is in fact something with fly.io then we could work towards building a docker image and just deploying to somewhere else like a digital ocean droplet or heroku or something. 

The complication here is postgres is being fly.io as well. So we'll have to setup redis and postgres in addition to the rails application.

**Comment by zach-c-d** [comment] 2023-08-23 00:23
If this doesn't break for N time then we could close this ticket?? say 2 weeks? @AcharyaS97 ? 

Perhaps we could create a selenium job to continually test this issue. Make a ShelterSignalMeasurement using the API and then check that the pop color has changed and it's displayed capacity has changed too.

**Comment by AcharyaS97** [comment] 2023-09-24 15:36
Sure.

**Comment by zach-c-d** [comment] 2023-10-04 21:07
This still seems to be working. I'm going to close this ticket for now.

**Closed as completed by zach-c-d** 2023-10-04 21:07 UTC
